<a href="https://colab.research.google.com/github/murtazaarsh7/ml_in_summers2026/blob/main/scratch_LINEAR_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import numpy as np
import pandas as pd

In [68]:
class MeraLR:
  def __init__(self):
    self.m=None
    self.b=None
  def fit(self,x_train,y_train):
    num=0
    den=0
    total=0
    for i in range(x_train.shape[0]):
      num+=(x_train[i]-x_train.mean())*(y_train[i]-y_train.mean())
      den+=(x_train[i]-x_train.mean())**2
    self.m=num/den
    self.b=y_train.mean()-(self.m*x_train.mean())
    print(self.m,self.b)
  def predict(self,x_test):
    y_predict=self.m*x_test+self.b
    return y_predict


In [69]:
df=pd.read_csv('/content/drive/MyDrive/Placement.csv')

In [70]:
df.sample(5)

,cgpa,package
4,6.94,3.57
10,5.32,1.86
2,7.82,3.25
9,8.31,3.51
11,6.61,2.60


In [71]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values

In [72]:
x,y

(array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
        6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94]),
 array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
        2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98]))

In [73]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [74]:
lr=MeraLR()
lr.fit(x_train,y_train)

0.49513785623297796 -0.6392610314300495


In [75]:
from sklearn.linear_model import LinearRegression

In [76]:
lr_1=LinearRegression()

In [77]:
lr_1.fit(x_train.reshape(-1,1),y_train)

LinearRegression()

In [78]:
m_1=lr_1.coef_
m_1

array([0.49513786])

In [79]:
b_1=lr_1.intercept_
b_1


np.float64(-0.6392610314300486)

In [80]:
y_pred_0=m_1*x_test[0]+b_1
y_pred_0

array([3.47533455])

In [81]:
print(lr.predict(x_test[0]))

3.475334553865997


MeraLR is performing same as LR from sklearn